name: First portfolio deploy project

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v1

    - name: Configure AWS credentials
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: ap-south-1

    - name: Deploy static site to s3 bucket
      run: aws s3 sync . s3//tws-kajal-portfolio --delete
    
